inherit_from: .rubocop_todo.yml
AllCops:
  # Include:
  #   - '**/RakeFile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
Rails:
  Enabled: true
Style/VariableNumber:
  EnforcedStyle: 'normalcase'
