inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Include:
  #   - '**/RakeFile'
    - '**/config.ru'
  Exclude:
    - '.rbenv/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Style/VariableNumber:
  EnforcedStyle: 'normalcase'
