language: ruby

cache: bundler

rvm:
  - 2.1.1
 
env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

notifications:
  email:
    recipients:
      - hdfelix@gmail.com

addons:
  postgresql: '9.3'

before_script:
  - psql -c 'create database ypreg_test;' -U postgres
  - mkdir -p shippable/testresults
script:
  # - xvfb-run bundle exec rspec spec/*.rb -o shippable/testresults/results.xml
  - rspec spec/*
notifications:
  email:
    recipients:
      - hdfelix@gmail.com
after_success:
  - git push -f git@heroku.com:ypreg.git master
