language: ruby

cache: bundler

rvm:
  - "2.1.1"

# branches:
#   only:
#     - setup-travis

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database ypreg_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

# special command so that tests that require a GUI (e.g., a browser) can run
# For more info, see: [this page](http://docs.travis-ci.com/user/gui-and-headless-browsers/)
script:
  - xvfb-run bundle exec rspec spec/controllers/*.rb
  - xvfb-run bundle exec rspec spec/models/*.rb
  - xvfb-run bundle exec rspec spec/features/*.rb
