development:
  adapter: postgresql
  encoding: unicode
  database: ypreg_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ypreg_test 
  pool: 5
  username: postgres
  password:
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: ypreg_production
  pool: 5
  username: postgres 
  password:

