# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72d5733eb687c8fcdc15c1c9e75dfe5b2c98f315c682e5acbaf16da9593882f1a3b0c75aae0b74b44b0045282672eb73554bc1d035c4ae53a843889afa2c1fdb

test:
  secret_key_base: 9ad67c708f4eee9cd66a78b21283cee4cc8c16eb6878d67dcacf249b32a92b0a8da8f825a6904d5ae4e559811215b35c0c3c6ed3d2daa4559fb53c2ee2c1d036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
